### ISSUE TITLE
Redhat Dependencies

### ISSUE THREAD

**Issue by hackdefendr** [Cacti/documentation#1]
Just a short note to make sure people know that php-process is the Redhat / CentOS package to install for the php-posix dependency requirement.

**Comment by Linegod** [comment]
Noted.

**Comment by jpobeda** [comment]
@netniV , this is now included on CentOS instructions section. Shall we re word it to include RHEL7 ?

**Comment by netniV** [comment]
CentOS is effectively RHEL, so there should be little difference.  If it's now included, I'll close this issue.
