### ISSUE TITLE
Cacti Reset Graph Every week

### ISSUE THREAD

**Issue by jauharuddien** [Cacti/documentation#144]
Some have experienced that the graph is reset every week, so that the graph is only available for one week and every Sunday the graph repeats itself from the beginning. This happens in some of the graphs, the rest are normal.
![bug mrtg](https://user-images.githubusercontent.com/42039646/128665969-0c726948-92dc-495c-870b-f775f51e9f49.png)

**Comment by netniV** [comment]
This is the documentation repo which handles documentation problems.
