### ISSUE TITLE
Missing screenshots: SNMP Data Query Walkthrough

### ISSUE THREAD

**Issue by roscokhan** [Cacti/documentation#153]
[Not sure if this should be a 'missing' link or 'bug' report - it relates to partial missing content within documentation set]

# Describe the link

SNMP Data Query Walkthrough

## Old Link

https://docs.cacti.net/How-To-New-SNMP-Data-Queries.md

## New Link

https://docs.cacti.net/How-To-New-SNMP-Data-Queries.md (no change)

## Screenshots

Under text: "Now save this file and lets turn to cacti to implement this one. First, go to Data Queries to see"

there should be a screenshot or image, however the img ALT text appears instead.  The declared image source should be: "doc-images/dq-01.preview.png", however this image appears to not exist (404 error).

In total, I found 31 such instances of images displaying img ALT text instead of the intended image.

## Additional context

Makes it hard to recommend to clients and advocate against the clients moving to alternate monitoring platforms.

**Comment by netniV** [comment]
Thanks for reporting this, I have applied a fix to the code but unfortunately am having some technical issues getting to the webserver itself to update the code.  This will be sorted over the weekend and resolved.

**Comment by roscokhan** [comment]
Hi Mark,

Many thanks.

I notice this issue also with the "Script Data Query Walkthrough" page at this location too: https://docs.cacti.net/How-To-Script-Data-Queries.md
Cacti® - The Complete RRDTool-based Graphing Solution<https://docs.cacti.net/How-To-Script-Data-Queries.md>
Script Data Query Walkthrough. Goal of this HowTo will be to show the principles of writing a Script Query, including script, xml and all needed templates.Why should you create such a thing? Suppose, your target features some indexed readings, that are not available via SNMP but by some other method (e.g. wget/cgi, ssh, NRPE, …). Writing a Script Data Queries works very much the same way as ...
docs.cacti.net

There may be others - I'll make you aware of them if I find any more.


Regards,


Ross


________________________________

**Comment by netniV** [comment]
It's a global fix that will take effect once we update the site. There is also a fix for a table layout issue too

**Comment by roscokhan** [comment]
OK - thanks Mark.  🙂

________________________________

**Comment by netniV** [comment]
This is now corrected.

![image](https://user-images.githubusercontent.com/9052188/150900338-cbc2686d-7e99-42c7-a38d-a8a327f22f83.png)

**Comment by roscokhan** [comment]
Thanks, Mark

Verified.


Many thanks,


Ross

________________________________
