### ISSUE TITLE
Documentation on Data Input Methods updates.

### ISSUE THREAD

**Issue by ballanty** [Cacti/documentation#167]
# Describe the bug

The documentation lists four items as being available when creating a new "Data Input Method"

## To Reproduce

Go to:  Data Collection -> Data Input Method -> '+' to add 

Note that "Input Type" pull down list contains "Script/Command" and "Script Server"

## Expected behavior

In Chater 11, Table 11-1 Item "Input Type" the manual says:

"Select the type of data input method you are trying to create. Valid options here are 'Script/Command', 'SNMP', 'SNMP Query', and 'Script Query'."

(As an aside to this specific issue the sentence before the table says "To create a new data input method, select the Data Input Methods option under the Management heading. Once on that screen, click Add on the right. You will be presented with a few fields to populate on the following screen." but the "Data Input Method" item is under the "Data Collection" category on my system as well)

## Environment 

- Cacti Server running on FreeBSD 13.1
- Browser: Google Chrome
- Cacti Version: 1.2.22

**Comment by netniV** [comment]
That is correct, the Input Method is under Data Collection.  It was likely moved there a while ago.  

Are you willing to provide a Pull Request with the changes you suggest?

**Comment by ballanty** [comment]
Hi Mark,

  I should be able to do that.  Although I've seen Cacti for a while it's
the first time I'm setting up and administering.  Someone should really
check my pull requests carefully.

Cheers,
Rob

**Comment by ballanty** [comment]
This may be due to looking at outdated (but still available on the website) documentation.

On https://docs.cacti.net/, I navigated Support -> Manuals -> Cacti Manual (html)  this results in going to this URL: https://www.cacti.net/downloads/docs/html/.  The document is dated 2013.  There were other choices there as well (text, pdf).

It appears similar (but different and probably already updated info) is available if I navigate: Support ->  Documentation.

If the "Manual" is not intended to be current, perhaps the correct action would be to remove the old manual in its entirety. 

I cannot find documentation source for the old Manual either, so if it should still be correct please point me to its source and I'll happily update it.

**Comment by netniV** [comment]
This repo relates directly to https://docs.cacti.net/ which is the newer version of the manual.  I guess we should be removing the older one which was kept for historical people still running versions from long ago.  If you look through the docs site, and see the same issues, then you can create the pull request against this repo.  

If you feel they have been fixed, then feel free to close this issue.

**Comment by ballanty** [comment]
Sounds good. I’ll close. Thank you.
