### ISSUE TITLE
single-syslog-deployment.png is a JPEG file and seems unused

### ISSUE THREAD

**Issue by paulgevers** [Cacti/documentation#168]
The Debian linter (lintian) reports that the file images/single-syslog-deployment.png is actually a JPEG file:
```
images $ file single-syslog-deployment.png
single-syslog-deployment.png: JPEG image data, JFIF standard 1.01, resolution (DPI), density 120x120, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=4], baseline, precision 8, 443x380, components 3
```
Before renaming the file, I tried to locate where it's used, but I didn't quickly spot it. So instead of fixing the extension, removal might also be a solution.

**Comment by netniV** [comment]
@bmfmancini This seems like something you could handle easily.

**Comment by bmfmancini** [comment]
Image reuploaded in https://github.com/Cacti/documentation/pull/171
