### ISSUE TITLE
从模板创建聚合 无法显示、无法选取新创建的Aggragate模板

### ISSUE THREAD

**Issue by xu1412** [Cacti/documentation#173]
# Describe the bug
version： cacti-1.2.23
![image](https://user-images.githubusercontent.com/107183321/217404545-9b833a45-203a-4523-93b8-563f53915848.png)
这里的AG-tpl2 是新创建的模板，然后选择Create Aggregate from Template时，无法显示同时也无法选取新创建的模板AG-tpl2
![image](https://user-images.githubusercontent.com/107183321/217404938-2808eca6-841d-474f-812f-58f2850846ac.png)

**Comment by TheWitness** [comment]
Look the the browsers debug console for JavaScript errors.

**Comment by xu1412** [comment]
![image](https://user-images.githubusercontent.com/107183321/217459401-8c5389ed-4d4c-4c5b-bbf0-dca5f0dbc07e.png)
   貌似只能以该图形模板绑定的聚合模板才能显示出来

**Comment by xu1412** [comment]
![image](https://user-images.githubusercontent.com/107183321/217460062-4651b6d1-6234-4f02-b883-c8508949d735.png)
![image](https://user-images.githubusercontent.com/107183321/217460067-0b0349d9-f164-4c88-9813-7acb5a0cfd6b.png)

**Comment by netniV** [comment]
This is not a documentation issue.  Please open the issue in the correct repository, and where possible, please do so in English to allow our developers a better understanding of what is occurring.

**Comment by xu1412** [comment]
![image](https://user-images.githubusercontent.com/107183321/218417333-a32c5b52-79bd-4f19-99ea-ff6009e1e2a8.png)
![image](https://user-images.githubusercontent.com/107183321/218417334-68e69574-9155-41ce-99fb-86380eeb438e.png)
导入备份文件
source   sql 文件报错；这种需要处理吗；如何处理？
