### ISSUE TITLE
Aggregate Nth Percentile cannot produce Outbound

### ISSUE THREAD

**Issue by seyma-n** [Cacti/documentation#175]
# Describe the bug

I follow the Cacti document about **Variables**, `aggregate` should calculate the Nth percentile by summing like data source names row for row from each data source defined on the graph and then returning the highest Nth percent value calculated for like data source names. Instead, when I combine two graphs together for the 95th Percentile, I face the issue below:

1. The result only shows the 95th Percentile for Inbound, not Outbound.
2. I then manually added an additional `COMMENT: |95:bits:6:aggregate:2| Mbps` **with traffic_out** data source, still the value return is from Inbound.

## To Reproduce

1. Go to 'Console'

2. Click on 'Graphs' under 'Management'

3. Try to select 2 graphs or more (with 95th Percentile template), then scroll down and choose  'Create Aggregate Graph' from the dropdown menu, then click 'Go'

4. With the Aggregate Graph setting, I choose 'Total Similar Data Sources' because I would like to have traffic_in and traffic_out produce separate values.

5. After complete aggregate, as result it shows only the 95th Percentile for Inbound, not Outbound which is the problem. 

## Expected behavior

By using 'aggregate' variables for the 95th Percentile, it should show aggregate value for Inbound and Outbound separately.

## Screenshots

![image](https://user-images.githubusercontent.com/97157189/220536697-1331275d-185e-447c-80bb-7e953e23b38c.png)

![image](https://user-images.githubusercontent.com/97157189/220536435-734382eb-2598-4f0a-b0da-658bff984470.png)

## Desktop (please complete the following information)

N/A - Not related.

## Smartphone (please complete the following information)

N/A - Not related.

**Comment by netniV** [comment]
This is not a documentation issue.
