### ISSUE TITLE
Install on FreeBSD

### ISSUE THREAD

**Issue by xmacan** [Cacti/documentation#2]
In manual is old and innacurate information about FreeBSD. 
First method - freebsd ports:
You need only few ports and others will be installed automatically:
/usr/ports/database/mysqlXY-server   (XY means 56, 57,80, ... for example mysql56-server)
or
/usr/ports/database/mariaXYZ-server (XYZ means 100,101, ... for example  mysql101-server)

/usr/ports/net-mgm/cacti
and
/usr/ports/net-mgm/cacti-spine

PHP, snmp, .. will be installed automatically. 

Second method is via package. You need this:
pkg install mysqlXY-server (or maria)
pkg install cacti
pkg install cacti-spine

**Comment by netniV** [comment]
Hi @xmacan, I recently split the documentation up into more manageable pages.  You should be able to create a pull request with the changes you've suggested.
