### ISSUE TITLE
Boost documentation 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/documentation#58]
Hey Guys 

on the boost plugin page it gives advice on how to setup your DB 

{
 The important thing here is that memory tables store the full size of the column, even though the column type is varchar(). By default it's varchar(512). Therefore, if your system only needs 50 bytes, you will have 90% waste in your poller_output_boost table.

The next step would me to modify the structure of your poller_output and poller_output_boost tables. You would do this by doing the following:

alter table poller_output, modify column output varchar(50) not null default ””, engine=memory;

alter table poller_output_boost, modify column output varchar(50) not null default ””;

It's also important that the poller_output table is converted to memory, eliminate any disk I/O related to poller updates.

Now, you need to determine how many polling cycles will fit into your poller_output_boost table. In this case, when sizing the poller_output_boost table, you take the output column width and add 34 bytes per record. So, in this case, each data source result to be stored in the poller_output_boost table would take 84bytes. 
}

However, I don't think this is relevant anymore since this is the new default db scheme

MariaDB [cacti]> describe poller_output;
+---------------+-----------------------+------+-----+---------------------+-------+
| Field         | Type                  | Null | Key | Default             | Extra |
+---------------+-----------------------+------+-----+---------------------+-------+
| local_data_id | mediumint(8) unsigned | NO   | PRI | 0                   |       |
| rrd_name      | varchar(19)           | NO   | PRI |                     |       |
| time          | timestamp             | NO   | PRI | 0000-00-00 00:00:00 |       |
| output        | varchar(512)          | NO   |     |                     |       |

MariaDB [cacti]> describe poller_output_boost;
+---------------+-----------------------+------+-----+---------------------+-------+
| Field         | Type                  | Null | Key | Default             | Extra |
+---------------+-----------------------+------+-----+---------------------+-------+
| local_data_id | mediumint(8) unsigned | NO   | PRI | 0                   |       |
| rrd_name      | varchar(19)           | NO   | PRI |                     |       |
| time          | timestamp             | NO   | PRI | 0000-00-00 00:00:00 |       |
| output        | varchar(512)          | NO   |     | NULL                |       |
+---------------+-----------------------+------+-----+---------------------+-------+
4 rows in set (0.00 sec)

So the default DB is already optimized beyond what is recommended 
atleast in my view 

Can you confirm if i got this right ?

**Comment by TheWitness** [comment]
@bmfmancini, where is this documentation housed right now?  I'm not finding from the 'Performance' tab in Cacti.

**Comment by bmfmancini** [comment]
Hey Larry 

That is on the docs.cacti.net page 
https://docs.cacti.net/plugin:boost

**Comment by TheWitness** [comment]
He, don't read that ;)  I'm trying hard to kill that site, as are the other developers.  We need to publish the Packaging plugin for public consumption, and provide a landing page for people to publish their templates first though.

**Comment by bmfmancini** [comment]
I know I don't really read it but if someone were brand new to cacti they
could follow some of that documentation and cause problems on their system

Is there a way to mark it as deprecated or something like that?

**Comment by TheWitness** [comment]
Not yet, working on it.  Too much to do, so little time.

**Comment by bmfmancini** [comment]
Can I help on that ?
Like editor access or something

**Comment by TheWitness** [comment]
@bmfmancini, I would gladly give you the editor access on this repo, but that authority is delegated to @netniV  and @ronytomen at the present time.

**Comment by TheWitness** [comment]
Resolved here https://github.com/Cacti/documentation/commit/bc089e3e58a1fd9d1b448cd2586f9b348c221070
