### ISSUE TITLE
questions about Backup In windows

### ISSUE THREAD

**Issue by yagocordoba** [Cacti/documentation#59]
### Hi all
I want to back up our Cacti server and I have a couple of questions.  our backup software takes an initial copy of the data and then does differential data (the vendor calls this delta) with each scheduled snapshot.  Since Cacti has its own SQL database is there a plugin or agent that needs to be evoked before the scheduled snapshot? Taking the snapshot while the database is active would give an unreliable or failed backup nor do I want to risk corrupting the production database.  We are running Cacti off a Virtual Windows Server 2019.  Can a scheduled backup from within Cacti be scheduled?  Again, my biggest concern is for the snapshot and backup of data doesn't happen while the Database is in use.  The backup window is usually about 20 mins; ideally, I would like for the database transactions to stop just before the snapshot is taken.  The backup method takes a snapshot of the whole partition to allow for a complete recovery.  
Can you please let me know the important files that need to be backed up for Windows system?

**Thank you in advance for your help in this matter.**

**Comment by cigamit** [comment]
This Issue Tracker is not a support forum.  Please ask this question on the Cacti forums.

**Comment by yagocordoba** [comment]
Hi
I am posting in forum but can you add this section about backups for Linux and Windows operative systems in documentation section?
Thanks!

**Comment by netniV** [comment]
This is more a setup issue for the environment than cacti itself. You can achieve that by change the poller schedule task to multiple schedules excluding the window you desire. So as cigamit has highlighted that’s less for the docs  and more a forums or advanced howto.
