### ISSUE TITLE
Cacti 1.2.9 SNMPv3 errors when changing multiple devices 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/documentation#69]
Hey guys 

I noticed that when you mass change devices the following error occours 

2020/03/05 20:41:00 - CMDPHP SQL Backtrace: (/host.php[70]:form_actions(), /host.php[284]:api_device_change_options(), /lib/api_device.php[333]:db_execute_prepared())
2020/03/05 20:41:00 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'snmp_security_level' in 'field list'
2020/03/05 20:41:00 - CMDPHP SQL Backtrace: (/host.php[70]:form_actions(), /host.php[284]:api_device_change_options(), /lib/api_device.php[326]:db_execute_prepared())
2020/03/05 20:41:00 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'snmp_security_level' in 'field list' 

The device will continue to show down and SNMPV3  although the information shows filled in the device form the device will show a snmp host error 

Steps to reproduce 

go to console 
select multiple devices 
click dropdown and select change device settings 
fill out snmpv3 options

Notice no error comes up but in the log you will see the dbexec failure and device wont work on snmp

**Comment by netniV** [comment]
@TheWitness is this a documentation issue?

**Comment by TheWitness** [comment]
@bmfmancini added the column on his own while trying to figure things out.  The only thing to be documented is that the column is interpreted and not stored in the database.  But no one should be messing with the database, so we should just close it.
