### ISSUE TITLE
Reconsile docs.cacti.net

### ISSUE THREAD

**Issue by ronytomen** [Cacti/documentation#7]
Time to throw out the old for the new!

Need to compare and add any missing information from [docs.cacti.net](https://docs.cacti.net) into the documentation.

Once that is completed the [docs.cacti.net](https://docs.cacti.net) site will be converted to be updated with this documentation from this repository for the latest release.

***File Status***
- [ ] [Command-Line-Scripts.md](https://github.com/Cacti/documentation/blob/develop/Command-Line-Scripts.md)
- [x] [Data-Input-Methods.md](https://github.com/Cacti/documentation/blob/develop/Data-Input-Methods.md)
- [x] [Data-Queries.md](https://github.com/Cacti/documentation/blob/develop/Data-Queries.md)
- [x] [Debugging.md](https://github.com/Cacti/documentation/blob/develop/Debugging.md)
- [x] [Documentation-Standards.md](https://github.com/Cacti/documentation/blob/develop/Documentation-Standards.md)
- [x] [Frequently-Asked-Questions.md](https://github.com/Cacti/documentation/blob/develop/Frequently-Asked-Questions.md)
- [x] [General-Installing-Instructions.md](https://github.com/Cacti/documentation/blob/develop/General-Installing-Instructions.md)
- [x] [Graph-Overview.md](https://github.com/Cacti/documentation/blob/develop/Graph-Overview.md)
- [x] [Graph-a-Single-SNMP-OID.md](https://github.com/Cacti/documentation/blob/develop/Graph-a-Single-SNMP-OID.md)
- [ ] [How-to-Graph-a-Custom-Collection-Script.md](https://github.com/Cacti/documentation/blob/develop/How-to-Graph-a-Custom-Collection-Script.md)
- [x] [How-to-Graph-Your-Network.md](https://github.com/Cacti/documentation/blob/develop/How-to-Graph-Your-Network.md)
- [x] [Installing-Under-Windows.md](https://github.com/Cacti/documentation/blob/develop/Installing-Under-Windows.md)
- [x] [PHP-Script-Server.md](https://github.com/Cacti/documentation/blob/develop/PHP-Script-Server.md)
- [x] [Plugin-Development.md](https://github.com/Cacti/documentation/blob/develop/Plugin-Development.md)
- [x] [Principles-of-Operation.md](https://github.com/Cacti/documentation/blob/develop/Principles-of-Operation.md)
- [x] [RRDTool-Specific-Features.md](https://github.com/Cacti/documentation/blob/develop/RRDTool-Specific-Features.md)
- [x] [Requirements.md](https://github.com/Cacti/documentation/blob/develop/Requirements.md)
- [x] [Spine.md](https://github.com/Cacti/documentation/blob/develop/Spine.md)
- [x] [Templates.md](https://github.com/Cacti/documentation/blob/develop/Templates.md)
- [x] [Upgrading-Cacti.md](https://github.com/Cacti/documentation/blob/develop/Upgrading-Cacti.md)
- [x] [User-Management.md](https://github.com/Cacti/documentation/blob/develop/User-Management.md)
- [x] [Variables.md](https://github.com/Cacti/documentation/blob/develop/Variables.md)
- [x] [Version-Specific-Release-Notes.md](https://github.com/Cacti/documentation/blob/develop/Version-Specific-Release-Notes.md)
- [x] [Viewing-Graphs.md](https://github.com/Cacti/documentation/blob/develop/Viewing-Graphs.md)

**Comment by jpobeda** [comment]
There are several `how to` files under [HowTo](https://docs.cacti.net/howto) that I think they mostly come from the forums  so instead of carrying old stuff around (they are pretty much copy and paste from Cacti's forum), might be better to add the HowTo-Guidelines.md and chuck a link to cacti's forum.

**Comment by netniV** [comment]
Can you give more detail/examples?

**Comment by jpobeda** [comment]
They all come from https://forums.cacti.net/viewforum.php?f=6

```markdown
[HOWTO] Install and configure the Net-SNMP agent for Windows
[HOWTO] Debug Windows NTFS permission problems
[HOWTO] Testing the PHP Script Server
[HOWTO] Graph multiple servers using an SNMP proxy
[HOWTO] Using SSH tunnels to graph a remote Unix server
```
Never mind, I'll push them anyway if they are under cacti.net doc site.

Maybe future 'How To' docs should go to a `contribs` folder where people can look after them If the original creator isn't updating it.

**Comment by netniV** [comment]
Create a section, "Community How-To's" maybe?  I'm not sure really.  I think keep the content.  It's on the forum but better if its in the docs to refer to were we verify the content.

**Comment by jpobeda** [comment]
@netniV should be adding all these new files to the list so we can flag those that need 'urgent' updates like the patch creation one =D

Shouldn't we making a distinction to those created by Cacti Group and those created by the community? Apart from the `Author:`, just a thought.

**Comment by jpobeda** [comment]
More on https://github.com/Cacti/documentation/pull/32

**Comment by jpobeda** [comment]
@netniV , I'm finishing a another missing walkthrough and this one has 2 attached files I'm not sure where to link them. I presume they'll be uploaded on this repo but I'm not sure what would be a suitable directory name, etc. Please advise.

[Link is](https://docs.cacti.net/manual:100:3a_advanced_topics.3b_snmp_data_query_walkthrough)

If you look at the very bottom there are 2 attached files.

`cacti_graph_template_host_mib_hrstoragetable.xml_.txt`

and 

`hrStorageTable.xml.gz`

**Comment by netniV** [comment]
`resources/xml`

**Comment by TheWitness** [comment]
@jpobeda, @netniV, @Linegod, @jimmy, @BSOD2600, @bmfmancini,

Do any of you guys have time to audit/work on some of the outstanding issue here?  I've been plowing through them in the last days, but I need another set of eye or two to check my math as it were, and to audit the layout of the manual for content and flow and verify if we've missed any chapters.  Any volunteers?

Larry

**Comment by bmfmancini** [comment]
@TheWitness  I  should have some time this week 
send me what you want to look at !

**Comment by TheWitness** [comment]
@bmfmancini, if you could do like @ronytomen did and make a sweep of the stock user interface, and then from there, take a sweep of the documentation and then in a single ticket, in bullet form, call out any problems you see with style and vocabulary, create a "todo" list as @ronytomen did as well calling out the pages that need work.

If you could do that, it would be greatly appreciated.  I'm going to continue to trudge along, but normal work starts tomorrow, so, obviously things are going to slow down.  I've made great progress in any event this weekend thus far.

**Comment by TheWitness** [comment]
Moving the last two tasks to the #89 and closing this one.
