### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by ronytomen** [Cacti/documentation#8]
In effort to move all documentation to this repository we need to reconsilate the installation instructions in the documentation with those on the [Cacti Repository Wiki](https://github.com/Cacti/cacti/wiki).

Merge the documentation updates from the Wiki to the documentation repository.

Once the installation instructions have been updated, the originals in the Wiki should be removed and a reference to the Documentation Repository should be created.

***Installation Methods***
- [ ] Prerequisites
   - [ ] Windows
   - [ ] Linux
      - [ ] Ubuntu
      - [ ] FreeBSD
      - [ ] CentOS
- [ ] Pre-Made Package Installer
   - [ ] Windows - NSIS Installer
   - [ ] Linux - apt/pkg/yum
- [ ] Source upgrades
- [ ] Plugins

**Comment by netniV** [comment]
This sounds like a good plan.  There will need for a new installation via command line too once I have completed the 1.2 CLI installer (should be by the weekend).

**Comment by netniV** [comment]
I've added some check boxes for the various things I think we need to cover/update.

**Comment by bmfmancini** [comment]
I have a few videos on cacti installation on my YT channel could these be included ?

**Comment by netniV** [comment]
Feel free to post links to them here, and we can review them.  At the moment, we haven't included any links to videos but that could change.  One of our members has created videos previously himself for older versions of Cacti which I have used to remind myself of things from time to time so they are useful.

**Comment by bmfmancini** [comment]
Sounds good to me!

Here are the videos I have 

https://www.youtube.com/watch?v=be8Pz5O4d8Y - cacti 1.1.5 install and server setup
https://www.youtube.com/watch?v=3M4RYG2PF9k - enable email alerts with the thold plugin
https://www.youtube.com/watch?v=8cCP4j6LKG0 - how to install cacti plugins
https://www.youtube.com/watch?v=xegaAJU1_MU - cacti 1.1.2 installation
https://www.youtube.com/watch?v=nateGK7xcnA - how to setup ldap authentication ( for 0.8x)
https://www.youtube.com/watch?v=kTJFnjPxYks - how to add devices to cacti
https://www.youtube.com/watch?v=bAWt4P1cft0 how to setup a debian server to be monitored with cacti

**Comment by oijkn** [comment]
Any of you have instructions on how to upgrade multi-poller, please? In this wiki I only see installation method.

**Comment by bmfmancini** [comment]
To update multi poller simply update the main poller

In two polling cycles the remote pollers will copy the files over from the
main poller

Make sure to take full back ups of each db just to be safe

**Comment by TheWitness** [comment]
Closing this.  After review, I've found that the upgrade instructions have been updated to reference the Remote Data Collectors.  As far as the videos are concerned, I would be happy to receive a pull request @bmfmancini.
