### ISSUE TITLE
cacti 1.2.13 tree view problem

### ISSUE THREAD

**Issue by samohsin** [Cacti/documentation#85]
Gentlemen,I need help on cacti ver 1.2.13. I have several graphs in a tree. When i select tree mode & click on a specific tree, there are about 15 graphs in that one. I can view all the graphs in a preview mode. When the mouse cursor is on any graph, & i click on a particular graph it just zooms the graphs rather than opening the graph which was so in cacti 0.8.8b. I have to click on time view graph on the right side of each graph to view. I do not want this. I want the time view graph to be activated when i click the graph in the tree.what is the solution to this issue.

**Comment by cigamit** [comment]
You would probably have to create your own plugin for this, I don't see us ever going back to the old way, its been this way for years.

**Comment by cigamit** [comment]
Closing this, as it was created in the wrong repo.  This is the documentation repo, you would need to recreate it in the https://github.com/Cacti/Cacti repo.  Even then I don't think our answer is going to change.
