### ISSUE TITLE
Cacti report issue

### ISSUE THREAD

**Issue by oceanus121** [Cacti/documentation#87]
Hey!

There is Cacti report that i found there is gray area on the graphs, no idea what is that mean?
![graphs](https://user-images.githubusercontent.com/74708220/99647286-89c35500-2a8c-11eb-99c7-bc74c916ef59.JPG)

**Comment by oceanus121** [comment]
is that meaning the traffic drop ?

**Comment by cigamit** [comment]
Wrong repo, this is the documentation repo, even then this is not a Cacti bug, you should ask this in the forums (https://forums.cacti.net/).   When posting in the forums, please include more information about what Cacti version you are using, what plugins you are using, and what graph template you are using for that graph.
